name: Topher Morrison
favicon: null
layout_spectrum: 0.963
typography_spectrum: 0.31918
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4a5157'
    - '#000000'
    - '#858585'
    - '#f5881c'
  brandStrength: 0.6015659843105823
  lightness: 0.39216316980309784
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
